import { DM_Sans } from "next/font/google";
import "./globals.css";

const dmSans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
  variable: "--font-dm-sans",
});

export const metadata = {
  title: "Clara Kim's Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${dmSans.variable} font-sans antialiased min-h-screen`}
        style={{
          backgroundColor: 'hsla(0,0%,100%,1)',
          backgroundImage: `
            radial-gradient(at 40% 20%, hsla(275,34%,95%,1) 0px, transparent 50%),
            radial-gradient(at 80% 0%, hsla(280,54%,86%,1) 0px, transparent 50%),
            radial-gradient(at 0% 50%, hsla(240,13%,82%,1) 0px, transparent 50%),
            radial-gradient(at 80% 50%, hsla(240,0%,100%,1) 0px, transparent 50%),
            radial-gradient(at 0% 100%, hsla(268,34%,80%,1) 0px, transparent 50%),
            radial-gradient(at 80% 100%, hsla(240,0%,100%,1) 0px, transparent 50%),
            radial-gradient(at 0% 0%, hsla(235,31%,94%,1) 0px, transparent 50%)
          `,
          backgroundAttachment: 'fixed'
        }}
      >
        {children}
      </body>
    </html>
  );
}